### ISSUE TITLE
Run issue "No module named 'SoapySDR'"

### ISSUE THREAD

**Issue by onebiozz** [xmikos/soapy_power#27]
After installing soapy_power using python 3 i get this issue, SoapySDR is installed, along with simplesoapy (via pip), along with all other dependencies except for SciPy, i believe my environment path is set up right.

i installed this on a raspberry pi model 3

`Traceback (most recent call last):
  File "/usr/local/bin/soapy_power", line 11, in <module>
    load_entry_point('soapy-power==1.6.1', 'console_scripts', 'soapy_power')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/soapy_power-1.6.1-py3.5.egg/soapypower/__main__.py", line 5, in <module>
  File "/usr/local/lib/python3.5/dist-packages/SimpleSoapy-1.5.1-py3.5.egg/simplesoapy.py", line 5, in <module>
ImportError: No module named 'SoapySDR'`

my paths 

`$echo $PYTHONPATH
/usr/local/bin/python3
$ python3 -c "import sys; print(sys.path)"
['', '/usr/local/bin/python3', '/usr/lib/python35.zip', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-arm-linux-gnueabihf', '/usr/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/dist-packages', '/usr/local/lib/python3.5/dist-packages/SimpleSpectral-1.0.0-py3.5.egg', '/usr/local/lib/python3.5/dist-packages/SimpleSoapy-1.5.1-py3.5.egg', '/usr/local/lib/python3.5/dist-packages/soapy_power-1.6.1-py3.5.egg', '/usr/lib/python3/dist-packages']
`

**Comment by onebiozz** [comment]
Issue figured out, i needed to install `python3-soapysdr` specifically and not just SoapySDR, now it runs well
